### ISSUE TITLE
Wrong intersection results

### ISSUE THREAD

**Issue by jakubito** [anywhichway/intersector#2]
Hi,
I was trying out this package as I was intrigued by its speed. Unfortunately, I'm getting wrong results. [An example](https://jsfiddle.net/qbty2erL/11/):

```javascript
intersector()([1, 4], [2, 3], [2, 4])
```

returns `[4]`. Unless I'm missing something, it should return an empty array.

Other examples:

`[1, 4], [2, 3], [1, 4]` returns `[1, 4]` instead of `[]`
`[1, 2], [2, 3], [2, 1]` returns `[2, 1]` instead of `[2]`
`[1, 2], [], [2, 1]` returns `[2, 1]` instead of `[]`

I also tried `lovasoa` and `lodash` intersection functions and they both give correct results.

**Comment by anywhichway** [comment]
Ugh! You are correct. Will look at this today and revisit the unit tests.

Sent via the Samsung Galaxy S20 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by anywhichway** [comment]
@jakubito I have a fix. Doing far more unit tests. Will publish tomorrow. If I keep going tonight I will make more mistakes! Meanwhile, here are the performance numbers:

lodashPrimitive x 62.69 ops/sec ±3.88% (65 runs sampled)
benviePrimitive x 49.10 ops/sec ±2.88% (64 runs sampled)
lovasoaPrimitive x 123 ops/sec ±1.79% (78 runs sampled)
fastArrayIntersect x 84.02 ops/sec ±1.78% (72 runs sampled)
intersectorPrimitive x 136 ops/sec ±0.98% (76 runs sampled)
lodashObject x 48.05 ops/sec ±1.54% (62 runs sampled)
benvieObject x 47.04 ops/sec ±2.44% (61 runs sampled)
fastArrayIntersectObject x 79.27 ops/sec ±1.65% (68 runs sampled)
intersectorObject x 91.84 ops/sec ±1.55% (67 runs sampled)
fastArrayIntersectKeyedObject x 67.50 ops/sec ±1.24% (69 runs sampled)
intersectorKeyedObject x 126 ops/sec ±3.67% (81 runs sampled)
Fastest is intersectorPrimitive

**Comment by jakubito** [comment]
@anywhichway Nice work! Looking forward to see the algorithm 👍

**Comment by anywhichway** [comment]
@jakubito Ok, it is fixed and pushed. Thanks for reporting it. A lot of people would have just said $%^ and moved on. I added some comments about the algorithm in the README.
